#!/usr/bin/env bash

source "$(dirname "$0")/../scripts/internal/husky.sh"

handle_output() {
  local EXIT_CODE=$1

  if [[ "$RESULT" == *"__UPDATED__"* ]]; then
    SUCCESS_MSG="Unstable packages have been pinned"
  elif [[ "$RESULT" == *"__SKIPPED__"* ]]; then
    SUCCESS_MSG="No new unstable packages found"
  fi
}

run_step "Verifying lockfile" "Lockfile is verified" yarn install --immutable --immutable-cache
run_step "Formatting staged files" "Staged files are formatted" yarn lint-staged
